"""empty message

Revision ID: 014d4e519985
Revises: 38c4e85512a9
Create Date: 2019-10-11 23:55:31.376738

"""

# revision identifiers, used by Alembic.
revision = '014d4e519985'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
