"""empty message

Revision ID: 790d94eb54c4
Revises: 8cd20fa4fe7c
Create Date: 2019-10-12 23:48:12.561146

"""

# revision identifiers, used by Alembic.
revision = '790d94eb54c4'
down_revision = '8cd20fa4fe7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
