"""empty message

Revision ID: 90a5ba8cb31f
Revises: 014d4e519985
Create Date: 2019-10-12 17:15:09.307707

"""

# revision identifiers, used by Alembic.
revision = '90a5ba8cb31f'
down_revision = '014d4e519985'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
