import numpy as np

array = np.array([[1,2,3],[2,3,4]], dtype = int) 
zero = np.zeros((3,4))
print('dim:', array.ndim)
print('shape:', array.shape)
print('size:', array.size)
print('type:', array.dtype)
print(zero)

a = np.arange(12)
print('arange:', a)
a = a.reshape((3,4))
print('reshape\n', a)
a = np.linspace(0,10,10)
print(a)
a = np.arange(12).reshape((3,4))
b = np.arange(13,25).reshape((4,3))
c = np.dot(a,b)
c = a.dot(b)
print(c)
a = np.random.random((3,4))
print(a )

a = np.arange(12)
b = np.arange(13,25)
c = np.vstack((a, b))
d = np.hstack((a,b))
print(c)
print(d)